### ISSUE TITLE
Im trying to make pankekas and it fail on starting

### ISSUE THREAD

**Issue by klys** [lonesysadmin/python#1]
Hi,

Im trying to Make::Pankekas() and it fail everything its run.

Following all my devops its say that error is cause by a pollo level programing.

You should kill your self and avoid having sons.

So you can make a better world.

YopoPrograming

**Comment by lonesysadmin** [comment]
This is no longer an issue, as pankekas are ready to be made again using eggs and flour with a little bit of salt/suggar.
